### ISSUE TITLE
Consider a rename

### ISSUE THREAD

**Issue by DerpyChap** [yungnickyoung/Packie#1]
"Packie" read out loud is indistinguishable from [the slur used against people of Pakistani descent](https://en.wikipedia.org/wiki/Paki_(slur)), so it might be best to come up with a new name.

**Comment by yungnickyoung** [comment]
it aint that deep

**Comment by yungnickyoung** [comment]
(On a real note I appreciate the concern, but it's just a small Minecraft mod. I don't think anyone will take offense to it.)

**Comment by yungnickyoung** [comment]
Alright, I went ahead and renamed just to be safe. Hopefully this one doesn't offend anyone, lol.

**Comment by roboboredom** [comment]
paxi rolls of the tounge a lot nicer tbh lol
