### ISSUE TITLE
Load Order Formatting

### ISSUE THREAD

**Issue by gamerpotion** [yungnickyoung/Packie#12]
Hi, could you please write an example of the formatting to use when setting the loadOrder for datapacks and resourcepacks in the json file (Preferably on the Mod Page on CurseForge so new users can see)
Thanks

**Comment by yungnickyoung** [comment]
Hey, it's just a regular JSON list, where the items in each list are a string exactly matching the name(s) of the data/resource pack(s).

**Comment by gamerpotion** [comment]
> Hey, it's just a regular JSON list, where the items in each list are a string exactly matching the name(s) of the data/resource pack(s).

hey,  there seems to be an issue where it only selects the resource pack folder from inside paxi's folder,  if I try to make a zip resource pack from root resourcepack load first, it doesn't work and always uses paxi's pack first

**Comment by yungnickyoung** [comment]
oh boy. I'll take a look ASAP

**Comment by yungnickyoung** [comment]
1.18 or 1.19?

**Comment by gamerpotion** [comment]
> 1.18 or 1.19?

sorry this is on 1.19.2  - Paxi-1.19.2-Fabric-3.0.1.jar

Thanks

**Comment by yungnickyoung** [comment]
Can you elaborate on your exact use case? Including the packs you're loading, the exact behavior that's occuring, and what the problem is. Thanks!

**Comment by gamerpotion** [comment]
> Can you elaborate on your exact use case? Including the packs you're loading, the exact behavior that's occuring, and what the problem is. Thanks!

sure,  
to best explain it, are you able to get modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg
it might be easier to see

I updated Paxi on it and put the following code in the load order for resourcepacks.   It doesnt load Legacy Menu (which is stored in resourcepacks root folder) and always loads the folder from paxi folder.

`{
  "loadOrder": [ "DarkRPG Legacy Menu.zip" , "DarkRPG Nocturnal Data" , "RPG PVP Swords and Tools.zip" ]
}`

**Comment by gamerpotion** [comment]
> Can you elaborate on your exact use case? Including the packs you're loading, the exact behavior that's occuring, and what the problem is. Thanks!

hi, just wondering if you had a chance to look into this?

**Comment by gamerpotion** [comment]
Closing as no update on this and have now removed mod from modpack, so the issue is now redundant.
