### ISSUE TITLE
Feature Request: Remove Paxi Text

### ISSUE THREAD

**Issue by ghost** [yungnickyoung/Packie#14]
Hi, I bring you possibly the most absurd, meaningless, and time-wasting feature request in history:

![paxi](https://user-images.githubusercontent.com/108554062/218611842-e32b3d32-2d8c-4849-b39f-220901942d65.png)

Can you remove the (paxi) logo that inserts itself into pack descriptions? It's a little distracting and I don't think it serves any useful purpose.

**Comment by yungnickyoung** [comment]
It clarifies where the pack came from and how it got loaded. I think it's useful for players who aren't aware of paxi and may be confused as to how they have data packs loaded when they didn't load any themselves.

**Comment by ghost** [comment]
Fair enough. My pack design philosophy is to confuse players as little as possible by removing unfamiliar terms and content, but that perspective is also understandable.
