### ISSUE TITLE
[Suggestion] Update for 1.19.3/4 and 1.20.X?

### ISSUE THREAD

**Issue by mpustovoi** [yungnickyoung/Packie#16]
I have no alternative to this great mod as a helper to manage my small modpacks for my friends. 
Especially on 1.20.1

**Comment by Gamemassa** [comment]
I was gonna make an issue thread asking about a possible 1.20.x update but then I saw this thread. I also hope versions of Paxi for newer MC versions are on the way.

**Comment by enderpirate98** [comment]
I would also like this for my own modpack please!

**Comment by yungnickyoung** [comment]
Working on it now!

**Comment by yungnickyoung** [comment]
Done 👍

**Comment by enderpirate98** [comment]
Thanks so much!!!!
