### ISSUE TITLE
[Question] Do player loaded packs override packs loaded via Paxi, or is it the other way around?

### ISSUE THREAD

**Issue by StormDragon-64** [yungnickyoung/Packie#17]
_I already asked this on your discord server but that seems pretty in-active and no one responded, so I am asking here._
If a player loads a resource pack, will that resource pack override files in a Paxi loaded pack, or will the Paxi loaded resource pack override the player's installed resource pack(s)? 

In my case, I want the player's installed resource packs to take priority, so if this is not what happens by default, then this should be something that is configurable.

**Comment by StormDragon-64** [comment]
Answered on discord

**Comment by Linguardium** [comment]
you can provide the answer here too since not everyone uses discord :(
