### ISSUE TITLE
[BUG] Resourcepack_load_order.json and in-game load orders are not the same

### ISSUE THREAD

**Issue by JENOVAAbsolute** [yungnickyoung/Packie#21]
Minecraft: 1.20.1
Fabric Loader: 0.15.3
Fabric API: 0.91.0
Paxi: 4.0

Below is how I have the json. Verified through a json parser.
```
{
	"loadOrder": [
		"Visual Traveler's Titles.zip",
		"Embellished Stone",
		"Eclectic Trove.zip",
		"Snowy Grass Fix",
		"Footstep Sounds",
		"Eating Animations"
	]
}
```

Below is how it appears in-game. My OCD is killing me lmao.
![image](https://github.com/YUNG-GANG/Paxi/assets/60951301/df94b2b3-e47f-4885-bf48-4fa38b3d4212)

Latest.log
https://pastebin.com/KyG4EFkd

**Comment by Rafii2198** [comment]
It is kind of the same, it is the list read in reverse. I assume the Paxi just applies them one by one in order from first to last, meaning the first entry will end at the bottom and vice versa as the next entry is placed above it.
I do personally think that it should just read the list from the end so it reflects the order, it is a bit more logical.

**Comment by JENOVAAbsolute** [comment]
> It is kind of the same, it is the list read in reverse. I assume the Paxi just applies them one by one in order from first to last, meaning the first entry will end at the bottom and vice versa as the next entry is placed above it. I do personally think that it should just read the list from the end so it reflects the order, it is a bit more logical.

I am aware of the reverse order, and that isn't what I was referring to. That said, it doesn't even matter. This was caused by a typo in the config. It should say `Embellished Stone.zip`, and I forgot to add the .zip, so it was not accounted for.

I forgot to close this thread. Thank for the reminder. Have a good one.
