### ISSUE TITLE
Changelog shows Introducing NeoForge support!

### ISSUE THREAD

**Issue by ModernGamingWorld** [yungnickyoung/Packie#25]
![Screenshot 2024-05-09 213643](https://github.com/YUNG-GANG/Paxi/assets/75923060/d3caab2e-c0e7-4699-b2c0-4b16fc3fa35c)

Currently all your projects show NeoForge support, but are all marked as forge

**Comment by yungnickyoung** [comment]
The NeoForge projects have their own pages and are waiting on CF approval. In the meantime you can get them on my [modrinth](https://modrinth.com/user/YUNGNICKYOUNG)
