### ISSUE TITLE
It cannot adjust the resource pack order in Fabric 1.20.1

### ISSUE THREAD

**Issue by Huantanhua** [yungnickyoung/Packie#26]

**Comment by Fyoncle** [comment]
I have the same problem, load order just doesn't wanna work and paxi ignores it.

**Comment by YOUNIN15** [comment]
> I have the same problem, load order just doesn't wanna work and paxi ignores it.

Me too, were you able to solve?

**Comment by Fyoncle** [comment]
> > I have the same problem, load order just doesn't wanna work and paxi ignores it.
> 
> Me too, were you able to solve?

Yeah, you just have to syntax the json file good.

**Comment by YOUNIN15** [comment]
> > > I have the same problem, load order just doesn't wanna work and paxi ignores it.
> > 
> > 
> > Me too, were you able to solve?
> 
> Yeah, you just have to syntax the json file good.

YES, but what about the mods that add resourcepack, you can only change the order for resourcepack that is in the paxi folder, but not for another resourcepack that adds a mod as such.

**Comment by Fyoncle** [comment]
> > > > I have the same problem, load order just doesn't wanna work and paxi ignores it.
> > > 
> > > 
> > > Me too, were you able to solve?
> > 
> > 
> > Yeah, you just have to syntax the json file good.
> 
> YES, but what about the mods that add resourcepack, you can only change the order for resourcepack that is in the paxi folder, but not for another resourcepack that adds a mod as such.

You have to use the mod called [Resource Pack Overrides](https://modrinth.com/mod/resource-pack-overrides) mod for doing this type of built-in resource pack thingy, paxi is not able to do this.

**Comment by polykatt** [comment]
> > > I have the same problem, load order just doesn't wanna work and paxi ignores it.
> > 
> > 
> > Me too, were you able to solve?
> 
> Yeah, you just have to syntax the json file good.

I'm having the same problem, what do you mean by syntax the file good?

**Comment by yungnickyoung** [comment]
Closing because the discussion is pretty vague, please feel free to open your own individual issue reports with as much info as possible (version numbers, packs you're trying to load/modify, etc)
