### ISSUE TITLE
[1.21] [Fabric] Weird interaction between Sodium and Paxi forcing leaves to use Programmer Art textures

### ISSUE THREAD

**Issue by NoMoreStars** [yungnickyoung/Packie#31]
It seems to be an interaction specifically between Sodium 0.5.11 and Paxi 5.0.0. Tested with a clean install of Minecraft with no other mods included and got the same results. Will submit a new issue to the Sodium devs as well.

**Comment by yungnickyoung** [comment]
Between this and #30 as well as some user reports in the discord, it seems the 1.21 version may have issues loading builtin resources in an unexpected order. I'll try to look into it as soon as I can.

**Comment by polykatt** [comment]
I was just about to post this issue with Paxi causing the leaves of any texture packs to be ignored; displaying vanilla textures instead. I have this issue on 1.21.1 when the texture pack is loaded from the default 'resourcepacks' folder. If the pack is loaded from the paxi 'resourcepacks' folder it works fine though.

**Comment by yungnickyoung** [comment]
This should be fixed in v5.1.2. Please lmk if the problem persists!
