### ISSUE TITLE
[Help wanted] How the hell do I define the programmer art?

### ISSUE THREAD

**Issue by Cixon** [yungnickyoung/Packie#32]
Tried all the following below and nothing...

`"default"`
`"programmerart"`
`"programmer_art"`
`"programmer_art.zip"`
`"minecraft/resourcepacks/programmer_art.zip"`

**Comment by yungnickyoung** [comment]
Unfortunately Paxi doesn't currently support modifying the load order of built-in resource packs (#27 )

**Comment by Fyoncle** [comment]
> Tried all the following below and nothing...
> 
> `"default"` `"programmerart"` `"programmer_art"` `"programmer_art.zip"` `"minecraft/resourcepacks/programmer_art.zip"`

Use [Paxi Plus](https://modrinth.com/mod/paxiplus) :)
