### ISSUE TITLE
Datapack folder not loading

### ISSUE THREAD

**Issue by SylisMC** [yungnickyoung/Packie#4]
~~ive been having an issue where the data pack folder doesn't generate for some reason.. easy to fix, just create the folder manually but i thought you might wanna know about the issue.~~ Edit.

The latest version of paxi `Paxi-Fabric-1.17-1.2.1.jar` doesn't generate the datapack folder (if it doesn't exist) when you create/load a world

Downgraded to `Paxi-Fabric-1.17-1.2.jar` and the problem went away

**Comment by SylisMC** [comment]
Update, V1.2.1 doesn't actually appear to be working at all for datapacks. i had global datapacks load as soon as i downgraded my version

**Comment by yungnickyoung** [comment]
Hey, please try v1.2.2 and let me know if that fixes it.

**Comment by SylisMC** [comment]
Yup. Problems solved.
Folder is created, and data packs work again. Thanks

**Comment by SylisMC** [comment]
Mind you! dont forget you have v 1.2.1 marked as the latest.
