### ISSUE TITLE
Fabric's built-in datapack priority issue

### ISSUE THREAD

**Issue by alexmozaidze** [yungnickyoung/Packie#5]
Whenever I load a world with global datapacks, Fabric's default one takes priority over my custom datapacks. The issue is that if I want to change modded item's recipe to a custom one, it doesn't work unless I `/reload` , which is very inconvinient. I tried to change load priority in the `datapack_load_order.json` but it seems to only work with custom packs, not Fabric's built-in one.

**Comment by CammiePone** [comment]
Noticed this myself when trying to override a mod's existing datapack with my own using Paxi. It works fine if I put it directly on the world, but not if I have it loaded through Paxi. Not sure how this would be fixed, if it can be, but I do hope a fix comes soon.

**Comment by BrokenDawn627** [comment]
Can you fix this problem as soon as possible? I rely on this mod very much, thank you!

**Comment by NighthowlerStudios** [comment]
having similar behaviour in #6 but it's forge and can happen with other mods' namespaces too.

**Comment by bravely-beep** [comment]
I've also run into this issue, it's blocking me from adding the data overrides I need for my server

**Comment by yungnickyoung** [comment]
Apologies, I tried to address this a month or two ago and got lost in the data pack code sauce. I'll give it another attempt when I port to 1.19.

**Comment by yungnickyoung** [comment]
The mod has been rewritten to fix this issue and some other related issues in 1.19. Unfortunately due to the extent of the rewrite, this fix is not planned for previous versions.

**Comment by yungnickyoung** [comment]
Okay I lied. v2.1.0 should fix the issue :)
