### ISSUE TITLE
[Forge 1.16.5] Some datapacks load after paxi anyway

### ISSUE THREAD

**Issue by NighthowlerStudios** [yungnickyoung/Packie#6]
![image](https://user-images.githubusercontent.com/82226641/155973419-e51323d8-47cc-497d-a377-0bf2313e64e9.png)
this causes my KBPData pack to have its brutal bosses namespace ignored, making the brutalbosses unconfigurable.

**Comment by NighthowlerStudios** [comment]
https://github.com/someaddons/dungeonbosses/issues/7

**Comment by yungnickyoung** [comment]
Fixed in the 1.19 release. Please open another report if the issue persists.
