### ISSUE TITLE
Any chance of 1.19 support soon for fabric or at all?

### ISSUE THREAD

**Issue by TheFantasticLoki** [yungnickyoung/Packie#8]
Really loved using this mod in modpacks for 1.18 but I am moving on to making some packs for 1.19 and would like to utilize this mod starting with fabric as my first pack is focused on mostly vanilla++. After this ofc I'll likely attempt to make a forge pack that is balls to the wall but first things first. I would like this updated so I can utilise required resourcepacks that can't be disabled frivilously and automated datapacks for new worlds.

**Comment by yungnickyoung** [comment]
Released :)
